version: '3.6'
services:
  postgres:
    image: postgres:13
    ports:
      - '5832:5432'
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: trust

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.201.0.0/16
          gateway: 172.201.0.1

volumes:
  db_data:
